export {default as Hero} from './Hero'
export {default as Quotes} from './Quotes'
export {default as ContinueScroll} from './ContinueScroll'
export {default as Technologies} from './Technologies'
export {default as Testimoni} from './Testimoni'
export {default as PublicationInNumber} from './PublicationInNumber'