export const SIGNATURE_CONTAINER_TYPE = {
    SIMULATION_PLACE_USE_CASE: 'SIMULATION_PLACE_USE_CASE',
    DEPENDECY_USE_CASE: 'DEPENDECY_USE_CASE',
    SIMULATION_360_USE_CASE: 'SIMULATION_360_USE_CASE',
    BLOG_USE_CASE: 'BLOG_USE_CASE',
};
